### ISSUE TITLE
Windows 10 taking mouse focus to the send button of the send widget

### ISSUE THREAD

**Issue by CryptoCanary** [EverGreenCoinDev/EverGreenCoin#41]
See: https://github.com/EverGreenCoinDev/EverGreenCoin/commit/c3020a0908b185345bb843cc84d3b3e78787285c

**Comment by EverGreenCoinDev** [comment]
Testing of new Windows builds will be needed to determine if c3020a0 resolves this.

**Comment by EverGreenCoinDev** [comment]
Both 32-bit and 64-bit current (v1.8.0.1) Windows builds do exhibit this issue on Windows 10.

**Comment by EverGreenCoinDev** [comment]
Confirmed fixed in v1.9 Windows builds.
