### ISSUE TITLE
Make on Ubuntu missing QAction

### ISSUE THREAD

**Issue by ywarnier** [EverGreenCoinDev/EverGreenCoin#44]
Hi,

When making on Ubuntu 18.04 after following the environment config instructions in the install guide, I first get an error on QJsonDocument not being present (fixed by installing libqjson-dev).

Then I get the following:
```
In file included from src/qt/overviewpage.cpp:2:0:
build/ui_overviewpage.h:13:10: fatal error: QtGui/QAction: Aucun fichier ou dossier de ce type
 #include <QtGui/QAction>
          ^~~~~~~~~~~~~~~
compilation terminated.
Makefile:3513: recipe for target 'build/overviewpage.o' failed
make: *** [build/overviewpage.o] Error 1
```

I tried installing libqt5gui5 libqt5widgets5 libkf5guiaddons5 but these do not help.

Any idea what I'm missing?

**Comment by EverGreenCoinDev** [comment]
Hi @ywarnier, so very sorry for the slow response. I missed notification of your question.

It appears you are missing Qt libraries. Please make sure you meet all dependencies listed, https://github.com/EverGreenCoinDev/EverGreenCoin/blob/master/doc/readme-qt.rst

I hope this information is helpful and, again, sorry for the slow response.

**Comment by EverGreenCoinDev** [comment]
This should help and do all the work for you on Ubuntu: https://github.com/EverGreenCoinDev/EverGreenCoin/blob/master/doc/readme-qt.rst#ubuntu-bash-jumpstart

**Comment by ywarnier** [comment]
Looks good. Thanks!
