### ISSUE TITLE
issue

### ISSUE THREAD

**Issue by Cointopaydev** [EverGreenCoinDev/EverGreenCoin#49]
src/qt/charitydialog.cpp:13:25: fatal error: QJsonDocument: No such file or directory
 #include <QJsonDocument>
                         ^
compilation terminated.
make: *** [build/charitydialog.o] Error 1
​
we can't get the new to compile.

**Comment by CryptoCanary** [comment]
QJsonDocument is available as of Qt5. You need to upgrade from Qt4, it looks.

`qmake -v`
to verify your version.

**Comment by CryptoCanary** [comment]
There is an Ubuntu jumpstart script. Copy and paste into a shell:
`bash <(wget -qO- https://raw.githubusercontent.com/EverGreenCoinDev/EverGreenCoin/master/build-ubuntu.sh)`
